### ISSUE TITLE
#101 breaks foxy builds

### ISSUE THREAD

**Issue by Ace314159** [moveit/srdfdom#103]
#101 is a breaking change since it renames `DisabledCollision` and since there aren't any distro branches, foxy builds using `ros2` branch. 

I think the easiest solution would be to create a `foxy` branch without this change.

Pinging @henningkayser and @Abishalini since they were involved in #101.

**Comment by henningkayser** [comment]
@Ace314159 thanks for noticing this. You're right, a foxy branch is the way to go. I'll prepare one.

**Comment by henningkayser** [comment]
Foxy branch is there now, this issue can be closed when #105 is merged
