### ISSUE TITLE
Release for ROS2 Rolling

### ISSUE THREAD

**Issue by ijnek** [moveit/srdfdom#106]
Could one of the maintainers make a release for ROS2 rolling due to the API breaking changes that were made in https://github.com/ros-planning/srdfdom/pull/101? This seems like one of the things (if not the only thing) preventing moveit2 from being released on ROS2 Rolling. Thanks!

**Comment by JafarAbdi** [comment]
https://github.com/ros/rosdistro/pull/33105

**Comment by ijnek** [comment]
Thanks @JafarAbdi !
