### ISSUE TITLE
Release into kinetic

### ISSUE THREAD

**Issue by davetcoleman** [moveit/srdfdom#11]
This would help cleanup moveit's rosinstall file

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/12250

**Comment by davetcoleman** [comment]
Thanks!

**Comment by 130s** [comment]
Same version 0.3.1 also released into
Indigo https://github.com/ros/rosdistro/pull/12261
Jade https://github.com/ros/rosdistro/pull/12264
