### ISSUE TITLE
Change rosdistro for srdfdom in kinetic

### ISSUE THREAD

**Issue by davetcoleman** [moveit/srdfdom#20]
We just branch SRDFDom for Kinetic, so it needs to be updated in bloom 

see https://github.com/ros-planning/srdfdom/pull/18

**Comment by 130s** [comment]
Does this also mean `srdfdom` is ready for new release for IJK? I think version will be:
IJ: 0.3.4
K: 0.4.0

**Comment by davetcoleman** [comment]
I thought @mikeferguson [just said](https://github.com/ros-planning/moveit/issues/100#issuecomment-245758368) that branches must have different version numbers? I'm not sure where to look to find the rules on this (@wjwwood)

**Comment by wjwwood** [comment]
There aren't rules, it's just logical that two branches (which may be different) should not have the same version (which cannot be different).

**Comment by 130s** [comment]
Changed via bloom for Kinetic in https://github.com/ros/rosdistro/pull/12657

Also released are: 
I: https://github.com/ros/rosdistro/pull/12655
J: https://github.com/ros/rosdistro/pull/12658

**Comment by 130s** [comment]
Wait, doc and source jobs remain old for Kinetic.

**Comment by 130s** [comment]
Fixed https://github.com/ros/rosdistro/pull/12659
