### ISSUE TITLE
Release srdfdom into Melodic

### ISSUE THREAD

**Issue by clalancette** [moveit/srdfdom#34]
This is a friendly reminder that the Melodic buildfarm is [now available](https://discourse.ros.org/t/melodic-morenia-buildfarm-available/4248). It would be great to have a release of `srdfdom` into Melodic, as it is currently directly blocking 1 package and indirectly blocking 5 packages (http://repositories.ros.org/status_page/blocked_releases_melodic.html). Thank you!

**Comment by rhaschke** [comment]
I'm willing to help out on this, if @130s doesn't find time by the end of the week.
However, I will need permissions on the release repo.

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/17301

There has been no new changes on `kinetic-devel` branch since the last release into Kinetic (last commit: https://github.com/ros-planning/srdfdom/commit/0ade5951a3a9e58c251a83ad2047fb27febe0bcb), so I just ran `bloom`.
