### ISSUE TITLE
Use common FindTinyXML.cmake module

### ISSUE THREAD

**Issue by wjwwood** [moveit/srdfdom#4]
There is a new package called cmake_modules, which we just created:

https://github.com/ros/cmake_modules

It provides a common FindTinyXML.cmake CMake module, which we should all try to use in order to prevent issues when doing things like cross-compiling.

This is a low priority, but a good idea. The package is available for Hydro and Groovy, it will be in public on the next sync.

**Comment by mikeferguson** [comment]
Implemented in 08d6282055b0a00e2c779de0d13a17e9547c6ba2. This can probably be closed (I don't have permission to)
