### ISSUE TITLE
Release srdfdom into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [moveit/srdfdom#58]
Would you mind releasing `srdfdom` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 40 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by rhaschke** [comment]
I might be able to spent some time on releasing package over the weekend, but I'm already lagging behind my schedule on rviz...

**Comment by tylerjw** [comment]
It would be nice to get this released for Noetic as parts of MoveIt depend on it.  It looks like it is ready to go and just needs to be bloomed.

**Comment by rhaschke** [comment]
Done: https://github.com/ros/rosdistro/pull/26244
@tylerjw, thanks for pushing this forward, particularly reviewing #60.
