### ISSUE TITLE
build.ros.org Webhook?

### ISSUE THREAD

**Issue by davetcoleman** [moveit/srdfdom#64]
@rhaschke why do we have webhooks setup for this repo to the ROS buildfarm? They seem to be failing like in https://github.com/ros-planning/srdfdom/pull/63

![image](https://user-images.githubusercontent.com/561060/90673830-81514900-e215-11ea-801b-b9c8bb2cb145.png)

Also there are no branch protection rules setup, I'll do that now...

**Comment by rhaschke** [comment]
I'm in favour of disabling PR builds on the build farm.

**Comment by davetcoleman** [comment]
just removed build.ros.org
not sure about the travis-ci.org thing, i think that's deprecated also as we've moved to travis-ci.com

**Comment by rhaschke** [comment]
Yes, the travis-ci.**org** webhook can be removed. Just did it.
