### ISSUE TITLE
release indigo 0.2.7

### ISSUE THREAD

**Issue by tfoote** [moveit/srdfdom#7]
I've created an indigo-devel branch with the correct dependencies on console_bridge and urdfdom_headers for Saucy and Trusty. RE: https://github.com/ros/rosdistro/issues/4633

This needs to be released into indigo.

**Comment by mikeferguson** [comment]
This can probably be closed

**Comment by tfoote** [comment]
Yes, it's been released. https://github.com/ros/rosdistro/pull/4926
