### ISSUE TITLE
Galactic Release

### ISSUE THREAD

**Issue by DLu** [moveit/srdfdom#84]
Currently blocking moveit release

**Comment by tylerjw** [comment]
Before this can happen we need Galactic itself to be released.  If we want to release for rolling while we are waiting we can get a jump on being ready for that.

**Comment by v4hn** [comment]
As the ros2 releases get more mature, it's a *must* to release for rolling!
A rolling release is one of the great innovations of the ROS2 release process after all.

**Comment by henningkayser** [comment]
Galactic: https://github.com/ros/rosdistro/pull/29938
Rolling: https://github.com/ros/rosdistro/pull/29653
